# Generated by Django 4.1.3 on 2023-01-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_rename_apikey_userapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trips'),
        ),
    ]
